### ISSUE TITLE
[QWIK] Populating initial data?

### ISSUE THREAD

**Issue by jmcelreavey** [fabian-hiller/modular-forms#44] opened 2023-03-30 21:08 UTC
I'm trying to use my restaurant data that is returned in my resource but I can't seem to figure out how to do it 🤔 

```typescript
import { component$, Resource } from "@builder.io/qwik";
import { routeLoader$, z } from "@builder.io/qwik-city";
import { formAction$, useForm, zodForm$, type InitialValues } from "@modular-forms/qwik";
import { Button } from "~/components/base/Button";
import { Main } from "~/components/base/Main";
import { prisma } from "~/db";

const restaurantFormSchema = z.object({
    id: z.string().nonempty(),
    name: z.string().nonempty(),
    location: z.string().nonempty(),
    postcode: z.string().regex(/^[A-Z]{1,2}[0-9][0-9A-Z]?\s?[0-9][A-Z]{2}$/i),
    phone: z.string().regex(/^[0-9]{3}-[0-9]{3}-[0-9]{4}$/),
    doesDelivery: z.boolean(),
    addressLine1: z.string().optional(),
});

type RestaurantForm = z.input<typeof restaurantFormSchema>;

export const useRestaurantFormLoader = routeLoader$<InitialValues<RestaurantForm>>(() => ({
    id: "",
    name: "",
    location: "",
    addressLine1: "",
    postcode: "",
    phone: "",
    doesDelivery: false,
}));

export const useRestaurantFormAction = formAction$<RestaurantForm>(async (values) => {
    await prisma.restaurant.create({
        data: {
            name: values.name,
            location: values.location,
            addressLine1: values.addressLine1,
            postcode: values.postcode,
            phone: values.phone,
            doesDelivery: values.doesDelivery,
            relatedRestaurantId: values.id,
        },
    });
}, zodForm$(restaurantFormSchema));

export const useRestaurant = routeLoader$(async ({ params, redirect }) => {
    const restaurant = await prisma.restaurant.findUnique({
        where: {
            id: params.id,
        },
    });

    if (!restaurant) {
        console.log("redirecting user");
        throw redirect(301, "/");
    }

    return restaurant;
});

export default component$(() => {
    return (
        <Main>
            <Resource
                value={useRestaurant()}
                onPending={() => <div>Loading...</div>}
                onResolved={(restaurant) => {
                    const [, { Form, Field }] = useForm<RestaurantForm>({
                        loader: useRestaurantFormLoader(),
                        action: useRestaurantFormAction(),
                        validate: zodForm$(restaurantFormSchema),
                    });

                    return (
                        <Form>
                            <Field name="name">
                                {(field, props) => (
                                    <>
                                        <label for={field.name}>Your name</label>
                                        <input {...props} value={field.value} type="text" />
                                        <div>{field.error}</div>
                                    </>
                                )}
                            </Field>
                            <Field name="location">
                                {(field, props) => (
                                    <>
                                        <label for={field.name}>Your location</label>
                                        <input {...props} value={field.value} type="text" />
                                        <div>{field.error}</div>
                                    </>
                                )}
                            </Field>
                            <Field name="addressLine1">
                                {(field, props) => (
                                    <>
                                        <label for={field.name}>Your address line 1</label>
                                        <input {...props} value={field.value} type="text" />
                                        <div>{field.error}</div>
                                    </>
                                )}
                            </Field>
                            <Field name="postcode">
                                {(field, props) => (
                                    <>
                                        <label for={field.name}>Your postcode</label>
                                        <input {...props} value={field.value} type="text" />
                                        <div>{field.error}</div>
                                    </>
                                )}
                            </Field>
                            <Field name="phone">
                                {(field, props) => (
                                    <>
                                        <label for={field.name}>Your phone</label>
                                        <input {...props} value={field.value} type="text" />
                                        <div>{field.error}</div>
                                    </>
                                )}
                            </Field>
                            <Field name="doesDelivery">
                                {(field, props) => (
                                    <>
                                        <label for={field.name}>Does deliver?</label>
                                        <input {...props} checked={field.value} type="checkbox" />
                                        <div>{field.error}</div>
                                    </>
                                )}
                            </Field>

                            <Button>Send</Button>
                        </Form>
                    );
                }}
            />
        </Main>
    );
});
```

It doesn't seem possible as I need to basically give the values to the Loader which I don't have access to at this level?

**Comment by jmcelreavey** [comment] 2023-03-31 07:46
Problem with that is using Async causes TS to complain:
```
Argument of type '({ params, redirect }: RequestEventLoader<QwikCityPlatform>) => Promise<Restaurant>' is not assignable to parameter of type '(event: RequestEventLoader<QwikCityPlatform>) => ValueOrPromise<{ id: Maybe<string>; name: Maybe<string>; location: Maybe<string>; postcode: Maybe<string>; phone: Maybe<...>; doesDelivery: boolean | undefined; addressLine1: Maybe<...>; }>'.
  Type 'Promise<Restaurant>' is not assignable to type 'ValueOrPromise<{ id: Maybe<string>; name: Maybe<string>; location: Maybe<string>; postcode: Maybe<string>; phone: Maybe<string>; doesDelivery: boolean | undefined; addressLine1: Maybe<...>; }>'.
    Type 'Promise<Restaurant>' is not assignable to type 'Promise<{ id: Maybe<string>; name: Maybe<string>; location: Maybe<string>; postcode: Maybe<string>; phone: Maybe<string>; doesDelivery: boolean | undefined; addressLine1: Maybe<...>; }>'.
      Type 'Restaurant' is not assignable to type '{ id: Maybe<string>; name: Maybe<string>; location: Maybe<string>; postcode: Maybe<string>; phone: Maybe<string>; doesDelivery: boolean | undefined; addressLine1: Maybe<...>; }'.
        Types of property 'postcode' are incompatible.
          Type 'string | null' is not assignable to type 'Maybe<string>'.
            Type 'null' is not assignable to type 'Maybe<string>'.
```

**Comment by fabian-hiller** [comment] 2023-03-31 08:52
I will investigate this and see how it works even with an asynchronous function.

**Comment by fabian-hiller** [comment] 2023-03-31 18:24
Thanks for the tip!

**Comment by fabian-hiller** [comment] 2023-04-03 19:57
@jmcelreavey is the problem still there or has it cleared up? For me it works as intended. I am closing the issue, but will open it again if there are still problems.

**Closed by fabian-hiller** 2023-04-03 19:57 UTC
Labels: question

**Comment by promethyttrium** [comment] 2023-06-13 03:55
How do I do this with Solidjs?
