### ISSUE TITLE
interface does not satisfy the constraint FieldValues

### ISSUE THREAD

**Issue by kkharji** [fabian-hiller/modular-forms#2] opened 2022-11-13 16:28 UTC
Hello @fabian-hiller, very promising library and awesome documentation, thank you.

I'm using auto-generated interfaces for my types, but unfortunately I ran into an error:

```typescript
Type 'UserAuthLogin' does not satisfy the constraint 'FieldValues'.
Index signature for type 'string' is missing in type 'UserAuthLogin'.
```

The interface:

```typescript
export interface UserAuthLogin { login: string, password: string }
```

Thanks

**Comment by fabian-hiller** [comment] 2022-11-13 17:24
Hey @kkharji, thank you for using Modular Forms! That means a lot to me. I am aware of this problem. If you use a `type` instead of an `interface`, it works.

The problem is that a form can be nested arbitrarily and I use a recursive type for that. Why TypeScript doesn't then accept an interface as generic, I don't know yet. If you are familiar with TypeScript, you can try to help me here. Otherwise I will ask for advice in the SolidJS community.

**Comment by kkharji** [comment] 2022-11-13 18:17
Oh that sucks, I was hoping it was unknown issue. Yes, typescript advance type is hard to get right, let alone supporting `interface` keyword. 

No issues hopefully the rspc generator would be able to generate with `type` keyword. 

Thanks @fabian-hiller

**Comment by fabian-hiller** [comment] 2022-11-13 18:21
I am sure there is a solution to this problem. I will try to fix it tomorrow. I will give you an update here.

**Comment by fabian-hiller** [comment] 2022-11-13 20:01
As described in this [issue](https://github.com/microsoft/TypeScript/issues/15300), the "problem" has existed in TypeScript for a very long time now. I am not yet aware of a user-friendly workaround that does not compromise type safety. I will let you know as soon as I find a solution.

**Comment by fabian-hiller** [comment] 2022-11-20 16:41
Until TypeScript gives us a "better" solution, I recommend using `type` instead of `interface`. As an alternative, the workaround of giving an interface an explicit index signature can be used. Below are two examples.

```tsx
interface LoginForm {
  email: string;
  password: string;
  [name: string]: string;
}
```

```tsx
interface LoginForm extends Record<string, string> {
  email: string;
  password: string;
}
```

This may affect the editor support, so that e.g. autocomplete works only conditionally.

If someone here knows TypeScript very well and thinks he or she can solve the problem by making changes to Modular Forms, I have prepared a minimal [TypeScript playground](https://www.typescriptlang.org/play?#code/PQKhFgCgAIWg1AhgGwK4FNoBcCeAHTAewDNpFpiBLdZAEwDopZgpcDoAxaupNTAXibRhAH2gBnLACdKAOwDmQ0ROlz5AbQC6S6GNmoAtgCN0UnWKOFCydIlnno+5MgepZtdFVnpaDrjb9KGwAZSkkAbigoUAgYOF4MbHwiUiwAC0xiQikDCm5acUY4lkg2TC4aWgT0cWh+aABvHXVZRAN0AC4VGQVNLoqeFESxAaqh9C1dTnzq2pGZ8fEtSMgAXxXosCY4AGEpWywa7AzoAGNslLJoA0JaVGREKQps3PTELDPCWSxEOVrKLC1faIU5YSgAN0wkne6CKzCgxDcoMoXzOwMOHBeAB4ACqjWbQdAAD0O7lq+MWAD4ABQASkaOmAwGgO1umAy+ygqyikBi22gAEkPgB3bIAa1qwoBaWgAAMyrLtiUypwXgB1aU45J1BkwYSEgy-ZBdSQ9eQrfXQPCIcTiUVSWgm1QKFbcyDnWSSZ45DXpLXseqndHoTE5LGhgy+tL+9A02kbXlbOLQABCqA+skIIulcrkhykxBB6EVxSgedMhdO5XV0oF3wrRd1lvQhqCTrNFv11tt9sd3TUrqgHq9WR9tfrBcbgeDEfDNfSdfzldjdPCQA) for experimenting. I'm temporarily closing the issue until there are signs that changes to our code can fix the problem.

**Closed by fabian-hiller** 2022-11-20 16:41 UTC
Labels: bug, enhancement

**Comment by fabian-hiller** [comment] 2023-05-07 16:38
All solutions I know so far to be able to support interfaces reduce type safety. I have again experimented a bit, but have not come to a satisfactory solution.
