### ISSUE TITLE
Build error (qwik)

### ISSUE THREAD

**Issue by tuurbo** [fabian-hiller/modular-forms#28] opened 2023-03-22 20:08 UTC
`pnpm preview` returns this error: `❌ TypeError [ERR_INVALID_MODULE_SPECIFIER]: Invalid module "@qwik-city-plan" is not a valid package name imported from C:\_work\websites\_sandbox\qwik-gfs\node_modules\.pnpm\@builder.io+qwik-city@0.6.6_@builder.io+qwik@0.23.0\node_modules\@builder.io\qwik-city\index.qwik.mjs`

Version:
`@modular-forms/qwik: 0.1.1`

```
System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900HK
    Memory: 11.06 GB / 31.68 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.44)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @builder.io/qwik: 0.23.0 => 0.23.0
    @builder.io/qwik-city: 0.6.6 => 0.6.6
    undici: 5.21.0 => 5.21.0
    vite: 4.2.0 => 4.2.0
```

**Comment by fabian-hiller** [comment] 2023-03-22 20:20
Thank you for creating the issue. Earlier it worked. Currently the same error occurs on my machine. I suspect that the problem is on part of Qwik. I will create an issue there and link this one to it.

**Comment by RBleyenberg** [comment] 2023-03-23 21:36
Dear all,
have the same bug and tried some debugging on it...

If you that your complete example but uncomment the following it will work ( the build in preview) 

`//export const useLoginFormAction= formAction$<LoginForm>(() => { }, zodForm$(loginSchema));`

`    // const [, { Form, Field }] = useForm<LoginForm>({
    //     loader: useLoginFormLoader(),
    //     action: useLoginFormAction(),
    //     validate: zodForm$(loginSchema),
    // });`
    
   Gonna sleep now but maybe it helps a bit to hone in on the bug

**Comment by fabian-hiller** [comment] 2023-03-24 11:35
Since it is most likely a Qwik problem, I am closing this issue until there are other signs.

**Closed by fabian-hiller** 2023-03-24 11:35 UTC
Labels: bug

**Comment by fabian-hiller** [comment] 2023-03-30 17:30
According to the issue of me at Qwik, there is no fix yet. Probably it will take a few more days or a week. For more specific info, I would ask on Discord.

**Comment by tuurbo** [comment] 2023-03-31 17:55
@fabian-hiller 
Is it possible that updating the modular-forms lib dependencies to the latest qwik release could fix the issue?

This discord message by Manu might imply that 🤷‍♂️ https://discord.com/channels/842438759945601056/940654245265436732/1091321817504960625

**Comment by fabian-hiller** [comment] 2023-03-31 18:25
I will try to update the dependencies later.

**Comment by fabian-hiller** [comment] 2023-03-31 21:36
@tuurbo he new version is now available.

**Comment by tuurbo** [comment] 2023-04-01 00:05
@fabian-hiller Thanks for the update. Unfortunately it did not fix the error for me :/

```
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_MODULE_SPECIFIER]: Invalid module "@qwik-city-plan" is not a valid package name imported from C:\_work\websites\_sandbox\qwik-gfs\node_modules\.pnpm\@builder.io+qwik-city@0.100.0_@builder.io+qwik@0.100.0\node_modules\@builder.io\qwik-city\index.qwik.mjs
    at new NodeError (node:internal/errors:393:5)
    at parsePackageName (node:internal/modules/esm/resolve:788:11)
    at packageResolve (node:internal/modules/esm/resolve:811:5)
    at moduleResolve (node:internal/modules/esm/resolve:909:20)
    at defaultResolve (node:internal/modules/esm/resolve:1124:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_INVALID_MODULE_SPECIFIER'
}
```

**Comment by fabian-hiller** [comment] 2023-04-01 09:10
This error is now gone for me. However, I get another one: https://github.com/BuilderIO/qwik/issues/3483#issuecomment-1492642234
