### ISSUE TITLE
move() reordering breaks when a field array reaches 11 items long

### ISSUE THREAD

**Issue by kieran-mgc** [fabian-hiller/modular-forms#61] opened 2023-04-29 13:20 UTC
Stackblitz here: https://stackblitz.com/edit/modular-forms-solid-zapc6e?file=src/routes/todos.tsx

After a fieldarray reaches longer than 10 items the move() method seems to behave unexpectedly.

In the example stackblitz the last 3 items are:
8 tomatoes
9 tomatoes
10 tomatoes

When I call the method 
`move(form, 'todos', { from: 10, to: 8 })`

the last 3 times become 
9 tomatoes
8 tomatoes
9 tomatoes

**Comment by fabian-hiller** [comment] 2023-04-29 13:23
Thank you! I know what the problem is and will fix it in the next hour.

**Comment by fabian-hiller** [comment] 2023-04-29 14:25
The problem should be fixed now. Thanks again!

**Closed by fabian-hiller** 2023-04-29 14:25 UTC
Labels: bug
